<FloatLayout>:
    Image:
        source:"./images/home.jpg"


    BoxLayout:
        orientation: 'vertical'
        size: root.size
        Image:
            source:root.source

        Button:
            id: button1
            text: "enter ajilytics"
            font_size: 20
            on_press: root.buttonClicked()
            size_hint:0.3,0.3
            pos_hint: {"y":1,"right":0.65}
            color:(0,0,0,1)
            background_color: (0,153,255,0.5)